FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

RUN apt-get update && apt-get upgrade -y && \
    apt-get install postgresql -y && \
    apt-get install postgresql-common -y && \
    /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y && \
    apt-get clean


